language: go

go:
- 1.12.x

env:
- CGO_ENABLED=0

sudo: false

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go test ./...

script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
        curl -sL https://git.io/goreleaser | bash;
    fi
  
notifications:
  email: false
